# Generated by Django 4.2.15 on 2024-08-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='from_user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
